# coding: utf-8

"""
    AssistedSwarm

    Assisted swarm  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import assisted_swarm_client.assisted_swarm
from assisted_swarm_client.assisted_swarm.api.swarm_api import SwarmApi  # noqa: E501
from assisted_swarm_client.assisted_swarm.rest import ApiException


class TestSwarmApi(unittest.TestCase):
    """SwarmApi unit test stubs"""

    def setUp(self):
        self.api = assisted_swarm_client.assisted_swarm.api.swarm_api.SwarmApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_new_agent(self):
        """Test case for create_new_agent

        Create new agent.  # noqa: E501
        """
        pass

    def test_delete_agent(self):
        """Test case for delete_agent

        Delete agent.  # noqa: E501
        """
        pass

    def test_exit(self):
        """Test case for exit

        Exit the process.  # noqa: E501
        """
        pass

    def test_get_agent(self):
        """Test case for get_agent

        Get specific agent.  # noqa: E501
        """
        pass

    def test_health(self):
        """Test case for health

        Health check.  # noqa: E501
        """
        pass

    def test_list_agents(self):
        """Test case for list_agents

        List all running agents.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
