# coding: utf-8

"""
    AssistedSwarm

    Assisted swarm  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import assisted_swarm_client.assisted_swarm
from assisted_swarm_client.assisted_swarm.models.agent_list import AgentList  # noqa: E501
from assisted_swarm_client.assisted_swarm.rest import ApiException


class TestAgentList(unittest.TestCase):
    """AgentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentList(self):
        """Test AgentList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = assisted_swarm_client.assisted_swarm.models.agent_list.AgentList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
